name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-test:
    runs-on: macos-13

    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.1.app
      
    - name: Build and Test
      run: xcodebuild test -project Pom.xcodeproj -scheme "Pom" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO SWIFT_TREAT_WARNINGS_AS_ERRORS=YES OTHER_SWIFT_FLAGS="-D ED_SKIP_SWIFT_FORMAT" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14" ONLY_ACTIVE_ARCH=YES